### ISSUE TITLE
Sometimes unknown shapes show up (a question mark in the upper left corner)

### ISSUE THREAD

**Issue by planger** [eclipsesource/icat#40]
In some package exports, there is a `?` in the upper-left corner indicating that there is a wrong or broken element in the diagram.

Try e.g. exporting package `authorization`. Note that this can only be reproduced after #39

**Comment by eneufeld** [comment]
So I checked the code.
Right now the code in the export as well as in the Web App  is expecting to work on exactly one package.
I would suggest to refactor it to be able to handle multiple packages and maybe mark one package as the 'important' one. Also the https://github.com/eclipsesource/ecore-glsp/blob/master/server/glsp-ecore/src/main/java/com/eclipsesource/glsp/ecore/diagram/EcoreModelFactory.java must be adopted. 
So in order to fix this, we should discuss the way the graph should look like

**Comment by planger** [comment]
Wouldn't it the easiest solution for now to just create an SNode for each referenced class residing in another package to represent "imported" classes? Of course we'd have to disable the double-click handler for those classes, but that shouldn't be too hard.
Ideally this imported class would have a dedicated CSS class assigned so that we can visually style it differently to indicate that it is a class in another package. Also it would be good if the name of the class indicates that.
What do you think?

**Comment by eneufeld** [comment]
Should be fixed via https://github.com/eclipsesource/icat/commit/5594d610db114502f60d590ef33eb1082fc2b9d8
